import {
  Entity,
  Column,
  PrimaryGeneratedColumn,
  ManyToOne,
  ManyToMany,
  JoinColumn,
  OneToMany,
  OneToOne,
} from 'typeorm';
import { ActivityPackage } from './activity-package.entity';
import { Role } from 'src/workspace/entity/role.entity';
import { Argument } from './argument.entity';
import { ReturnValue } from './return-value.entity';

@Entity('activity_template')
export class ActivityTemplate {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @Column()
  name: string;

  @Column({ nullable: true })
  description: string;

  @Column()
  keyword: string; // VD: "open_browser", "upload_file_to_drive"

  @OneToMany(() => Argument, (arg) => arg.activityTemplate, { cascade: true })
  arguments: Argument[];

  @OneToOne(() => ReturnValue, (returnValue) => returnValue.activityTemplate, {
    cascade: true,
    nullable: true,
  })
  returnValue: ReturnValue;

  @ManyToOne(() => ActivityPackage, (pkg) => pkg.activityTemplates, { onDelete: 'CASCADE' })
  @JoinColumn({ name: 'activityPackageId' })
  activityPackage: ActivityPackage;

  @Column()
  activityPackageId: string;

  @ManyToMany(() => Role, (role) => role.activityTemplates)
  roles: Role[];

  // NEW: Keyword mapping fields
  @Column({ name: 'keyword_name', nullable: true })
  keywordName: string; // e.g., "Setup ERPNext Connection"

  @Column({ name: 'python_method', nullable: true })
  pythonMethod: string; // e.g., "setup_erpnext_connection"

  @Column({ name: 'is_auto_generated', default: false })
  isAutoGenerated: boolean; // true if generated from parsing

  @Column({ name: 'line_number', nullable: true })
  lineNumber: number; // line number in source file

  @Column({ nullable: true, default: 'activity' })
  type: string;

  @Column({ name: 'icon_code', nullable: true })
  iconCode: string;
}
