import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { Type } from 'class-transformer';

export class ArgumentResponseDto {
  @ApiProperty()
  id: string;

  @ApiProperty()
  name: string;

  @ApiPropertyOptional()
  description?: string;

  @ApiPropertyOptional()
  descriptionVi?: string;

  @ApiProperty()
  type: string;

  @ApiPropertyOptional()
  keywordArgument?: string;

  @ApiProperty()
  isRequired: boolean;

  @ApiPropertyOptional()
  defaultValue?: any;
}

export class ReturnValueResponseDto {
  @ApiProperty()
  id: string;

  @ApiProperty()
  type: string;

  @ApiPropertyOptional()
  description?: string;

  @ApiPropertyOptional()
  descriptionVi?: string;

  @ApiPropertyOptional()
  displayName?: string;

  @ApiPropertyOptional()
  displayNameVi?: string;
}

export class ActivityTemplateResponseDto {
  @ApiProperty()
  id: string;

  @ApiProperty()
  name: string;

  @ApiPropertyOptional()
  nameVi?: string;

  @ApiPropertyOptional()
  description?: string;

  @ApiPropertyOptional()
  descriptionVi?: string;

  @ApiProperty()
  keyword: string;

  @ApiProperty({ type: [ArgumentResponseDto] })
  @Type(() => ArgumentResponseDto)
  arguments: ArgumentResponseDto[];

  @ApiPropertyOptional({ type: ReturnValueResponseDto })
  @Type(() => ReturnValueResponseDto)
  returnValue?: ReturnValueResponseDto;

  @ApiPropertyOptional()
  type?: string;

  @ApiPropertyOptional()
  iconCode?: string;

  @ApiPropertyOptional()
  keywordName?: string;

  @ApiPropertyOptional()
  pythonMethod?: string;

  @ApiPropertyOptional()
  isAutoGenerated?: boolean;
}

export class ActivityPackageResponseDto {
  @ApiProperty()
  id: string;

  @ApiProperty()
  displayName: string;

  @ApiPropertyOptional()
  displayNameVi?: string;

  @ApiPropertyOptional()
  description?: string;

  @ApiPropertyOptional()
  descriptionVi?: string;

  @ApiPropertyOptional()
  imageKey?: string;

  @ApiPropertyOptional()
  imageUrl?: string;

  @ApiPropertyOptional()
  library?: string;

  @ApiPropertyOptional()
  version?: string;

  @ApiProperty()
  isActive: boolean;

  @ApiPropertyOptional()
  libraryS3Url?: string;

  @ApiProperty({ type: [ActivityTemplateResponseDto] })
  @Type(() => ActivityTemplateResponseDto)
  activityTemplates: ActivityTemplateResponseDto[];
}
